In [2]:
import pandas as pd
import glob
import os

In [4]:
chemin_dossier = r'C:\Users\User\Desktop\NRLAB_data_Louis-LESIAK\2022_data\Période 3'
liste_fichiers = os.listdir(chemin_dossier)
df_list = []
for nom_fichier in liste_fichiers:
    # Vérifiez que le fichier est un fichier dat
    if nom_fichier.endswith('.dat'):
        # Chargez le fichier dans un DataFrame
        df = pd.read_csv(os.path.join(chemin_dossier, nom_fichier), sep=',', header=[0], skiprows=[0,2, 3], low_memory=False)
        # Ajoutez le DataFrame à la liste
        df = df.loc [:,["TIMESTAMP","Batt_Li_Voltage","Batt_Li_Current","Batt_Li_Power","Batt_Li_SoC","PV_Voltage","PV_Power","Batt_Li_SetPower_EMS","LOAD_Current","PV_Current"]]
        df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])
        df = df[df['TIMESTAMP'].dt.second % 5 == 0]
        df_list.append(df)

df_final = pd.concat(df_list, ignore_index=True)

df_final

,TIMESTAMP,Batt_Li_Voltage,Batt_Li_Current,Batt_Li_Power,Batt_Li_SoC,PV_Voltage,PV_Power,Batt_Li_SetPower_EMS,LOAD_Current,PV_Current
0,2022-07-20 00:00:00,26.59,0.000,0.00,82.70,1.005,0.00,-76.73,0.084,0.000
1,2022-07-20 00:00:05,26.59,0.000,0.00,82.70,1.005,0.00,-76.73,0.084,0.000
2,2022-07-20 00:00:10,26.59,0.000,0.00,82.70,1.005,0.00,-76.73,0.084,0.000
3,2022-07-20 00:00:15,26.59,0.000,0.00,82.70,1.005,0.00,-76.73,0.084,0.000
4,2022-07-20 00:00:20,26.59,0.000,0.00,82.70,1.005,0.00,-76.73,0.083,0.000
...,...,...,...,...,...,...,...,...,...,...
120955,2022-07-26 23:59:35,25.10,0.942,23.65,19.24,25.080,0.68,21.76,0.870,0.027
120956,2022-07-26 23:59:40,25.10,0.943,23.67,19.24,25.080,0.65,21.76,0.870,0.026
120957,2022-07-26 23:59:45,25.10,0.950,23.85,19.24,25.070,0.68,21.96,0.878,0.027
120958,2022-07-26 23:59:50,25.10,0.950,23.85,19.23,25.070,0.68,21.96,0.878,0.027
120959,2022-07-26 23:59:55,25.10,0.950,23.85,19.23,25.070,0.68,21.46,0.858,0.027

In [5]:
df_final.to_csv('batterieDataPériode32.csv', index=False)

In [6]:
# Créez une liste pour stocker les DataFrames de chaque fichier
df_list = []

# Bouclez sur chaque fichier et chargez-le dans un DataFrame, puis ajoutez-le à la liste
for fichier in fichiers_csv:
    df = pd.read_csv(fichier, sep=',', header=[0], skiprows=[0,2, 3])
    df = df.loc[:, ['TIMESTAMP','RECORD','Batt_Li_Voltage', 'SEVolt_Batt_Li_Current','Batt_Li_Power','Batt_Li_SoC','Batt_Li_SetPower_EMS']]
    df['TIMESTAMP'] = pd.to_datetime(df['TIMESTAMP'])
    df = df[df['TIMESTAMP'].dt.second % 5 == 0]
    df_list.append(df)

# Concaténez tous les DataFrames dans la liste en un seul DataFrame
df_final = pd.concat(df_list, ignore_index=True)

# Afficher le DataFrame final
print(df_final)

NameError: name 'fichiers_csv' is not defined

In [7]:
df_final

,TIMESTAMP,Batt_Li_Voltage,Batt_Li_Current,Batt_Li_Power,Batt_Li_SoC,PV_Voltage,PV_Power,Batt_Li_SetPower_EMS
0,2021-12-31 00:00:00,25.60,-0.058,-1.48,19.85,0.039,0,0.00
1,2021-12-31 00:00:05,25.59,-0.058,-1.48,19.85,0.039,0,0.00
2,2021-12-31 00:00:10,25.60,-0.058,-1.48,19.85,0.040,0,0.00
3,2021-12-31 00:00:15,25.60,-0.059,-1.51,19.85,0.039,0,0.00
4,2021-12-31 00:00:20,25.60,-0.059,-1.51,19.85,0.039,0,0.00
...,...,...,...,...,...,...,...,...
1517991,2022-08-01 23:59:35,27.46,0.185,5.08,94.30,27.420,0.0,0.08
1517992,2022-08-01 23:59:40,27.46,0.185,5.08,94.30,27.410,0.0,0.08
1517993,2022-08-01 23:59:45,27.47,-0.084,-2.31,94.30,27.430,0.0,0.08
1517994,2022-08-01 23:59:50,27.46,0.186,5.11,94.30,27.410,0.0,0.08
1517995,2022-08-01 23:59:55,27.45,0.185,5.08,94.30,27.410,0.0,0.08